name: CryptoVault
main: cc.fortibrine.cryptovault.CryptoVaultPlugin
version: ${version}

api-version: '1.21.7'
author: FortiBrine

depend: [Vault, PlaceholderAPI]

libraries:
  - "com.j256.ormlite:ormlite-jdbc:6.1"
