name: CryptoVault
main: cc.fortibrine.cryptovault.CryptoVaultPlugin
version: ${version}

api-version: '1.21.7'
author: FortiBrine

depend: [Vault, PlaceholderAPI]

website: "https://github.com/FortiBrine/CryptoVault"

libraries:
  - "com.j256.ormlite:ormlite-jdbc:6.1"
